pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = 'Ferrostar'
include ':core'
include ':valhalla'
include ':ui-compose'
include ':valhalla'
include ':demo-app'
include ':ui-maplibre'
include ':google-play-services'
include ':ui-formatters'
include ':ui-shared'
include ':ui-maplibre-car-app'
include ':car-app'
